// Generated by https://quicktype.io

export interface Stats {
  activitiesEntered: PuneHedgehog;
  activitiesWon: PuneHedgehog;
  assists: TartuGecko;
  totalDeathDistance: PuneHedgehog;
  averageDeathDistance: PuneHedgehog;
  totalKillDistance: PuneHedgehog;
  kills: TartuGecko;
  averageKillDistance: PuneHedgehog;
  secondsPlayed: TartuGecko;
  deaths: TartuGecko;
  averageLifespan: PuneHedgehog;
  score: TartuGecko;
  averageScorePerKill: PuneHedgehog;
  averageScorePerLife: PuneHedgehog;
  bestSingleGameKills: BestSingleGameKills;
  bestSingleGameScore: BestSingleGameKills;
  opponentsDefeated: PuneHedgehog;
  efficiency: PuneHedgehog;
  killsDeathsRatio: PuneHedgehog;
  killsDeathsAssists: PuneHedgehog;
  objectivesCompleted: TartuGecko;
  precisionKills: TartuGecko;
  resurrectionsPerformed: TartuGecko;
  resurrectionsReceived: TartuGecko;
  suicides: TartuGecko;
  weaponKillsAutoRifle: TartuGecko;
  weaponKillsBeamRifle: TartuGecko;
  weaponKillsBow: TartuGecko;
  weaponKillsGlaive: TartuGecko;
  weaponKillsFusionRifle: TartuGecko;
  weaponKillsHandCannon: TartuGecko;
  weaponKillsTraceRifle: TartuGecko;
  weaponKillsMachineGun: TartuGecko;
  weaponKillsPulseRifle: TartuGecko;
  weaponKillsRocketLauncher: TartuGecko;
  weaponKillsScoutRifle: TartuGecko;
  weaponKillsShotgun: TartuGecko;
  weaponKillsSniper: TartuGecko;
  weaponKillsSubmachinegun: TartuGecko;
  weaponKillsRelic: TartuGecko;
  weaponKillsSideArm: TartuGecko;
  weaponKillsSword: TartuGecko;
  weaponKillsAbility: TartuGecko;
  weaponKillsGrenade: TartuGecko;
  weaponKillsGrenadeLauncher: TartuGecko;
  weaponKillsSuper: TartuGecko;
  weaponKillsMelee: TartuGecko;
  weaponBestType: PuneHedgehog;
  winLossRatio: PuneHedgehog;
  allParticipantsCount: PuneHedgehog;
  allParticipantsScore: PuneHedgehog;
  allParticipantsTimePlayed: PuneHedgehog;
  longestKillSpree: BestSingleGameKills;
  longestSingleLife: BestSingleGameKills;
  mostPrecisionKills: BestSingleGameKills;
  orbsDropped: TartuGecko;
  orbsGathered: TartuGecko;
  remainingTimeAfterQuitSeconds: TartuGecko;
  teamScore: TartuGecko;
  totalActivityDurationSeconds: TartuGecko;
  combatRating: PuneHedgehog;
  fastestCompletionMs: BestSingleGameKills;
  longestKillDistance: BestSingleGameKills;
  highestCharacterLevel: PuneHedgehog;
  highestLightLevel: PuneHedgehog;
  fireTeamActivities: PuneHedgehog;
  ErrorCode: any;
  error: any;
  Message: any;
}

export interface PuneHedgehog {
  statId: string;
  basic: Basic;
}

export interface Basic {
  value: number;
  displayValue: string;
}

export interface TartuGecko {
  statId: string;
  basic: Basic;
  pga: Basic;
}

export interface BestSingleGameKills {
  statId: string;
  basic: Basic;
  activityId: string;
}
